aws:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: ASDFGHJKL2QWERTYU
  secretKey: qwert6yuio8p6ashutyi3YjkL
  bucketName: elasticbeanstalk-ap-south-1-089591637283
    
    
app:
  uploadFilePath: C:\\temp\\s3-upload-file.txt
  fileName: s3-upload-file.txt